name: Publish Website to Web Hosting
on:
  push:
    branches:
      - al-rabbi-updateby-rasel
jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Run react build script
        run: yarn && yarn build && yarn cache clean &&  rm -rf node_modules/ && rm -rf .next/
        env:
          CI: false

      # Runs a set of commands using the runners shell
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: srv1.hostwev.com
          username: dashboard@dashboard.funnelliner.com
          password: N^DK9ytB4h*m
          protocol: ftp
          port: 21 # todo replace with your web hosts ftps port
         
